---
apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
  namespace: wordpress
  labels:
    app: wordpress
spec:
  type: ClusterIP
  selector:
    app: wordpress
    tier: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306