---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  wordpress_db_password: ZXhhbXBsZXBhc3M= 
  mysql_password: ZXhhbXBsZXBhc3M=
  mysql_random_root_password: MQ==